[package]
name = "contour"
version = "0.1.0"
authors = ["Matthieu Viry <matthieu.viry@cnrs.fr>"]
edition = "2018"

[dependencies]
geojson = "0.13"
lazy_static = "1.0"
serde_json = "^1.0"
rustc-hash = "1.0.1"
slab = "0.4"
